name: Bug Report
description: File a bug report.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to fill out this bug report!
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: What are the steps to trigger this bug?
      placeholder: |
        1. …
        2. …
        3. …
        …
      validations:
        required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      validations:
        required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What was the unexpected behavior (bug)?
      validations:
        required: true
  - type: textarea
    id: potential-solution
    attributes:
      label: Potential Solution
      description: Optional. Do you have a potential solution in mind?
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: |
        This project has a Code of Conduct that all participants are expected to
        understand and follow.
      options:
        - label: I agree to follow this project’s Code of Conduct.
          required: true
  - type: markdown
    attributes:
      value: Thank you for the report; you’re awesome!
